stages:
  - name: check configuration
    if: branch = travis
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - sudo apt-get update
  - sudo apt-get -y install zstd

jobs:
  include:
    - stage: check configuration
      before_script: source ./package/prepare.sh
      script: ./package/test.sh
    - stage: deploy
      before_script: source ./package/prepare.sh
      script: ./package/deploy.sh
