language: python

before_install:
  - ./package/prepare.sh

stages:
  - name: test
    if: branch = deploy
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ AND branch = master

jobs:
  include:
    stage: test
    script: ./package/test.sh
    stage: deploy
    script: ./package/deploy.sh