language: python

jobs:
  include:
    stage: prepare
    script: ./package/prepare.sh
    stage: test
    script: ./package/test.sh
    stage: deploy
    script: ./package/deploy.sh

stages:
  - name: prepare
  - name: test
    if: branch = deploy
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ AND branch = master
