stages:
  - name: prepare
  - name: check aur keys
    if: branch = deploy
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ AND branch = master

jobs:
  include:
    - stage: prepare
      script: ./package/prepare.sh
    - stage: check aur keys
      script: ./package/test.sh
    - stage: deploy
      script: ./package/deploy.sh
