language: python

stages:
  - name: check_aur
    if: branch = deploy
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ AND branch = master

jobs:
  include:
    - state: prepare
      script: ./package/prepare.sh
    - stage: check_aur
      script: ./package/test.sh
    - stage: deploy
      script: ./package/deploy.sh
